apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        resources:
          limits:
            cpu: 0.5
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value: yourpassword
        - name: MYSQL_DATABASE
          value: app
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          # name must match the volume name below
        - name: mysql-persistent-storage
            # mount path within the container
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          # persistentVolumeClaim:
          #   claimName: mysql-claim
          gcePersistentDisk:
          # This GCE PD must already exist.
            pdName: mysql-disk
            fsType: ext4
